# -*- mode:python -*-

# Copyright (c) 2020 University of Illinois
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Authors: Andrew Smith

Import('*')

if env['TARGET_ISA'] == 'null':
    Return()

SimObject('PowerPredictor.py')

DebugFlag('PowerPred')
DebugFlag('TestPowerPred')
# DebugFlag('SimpleHistoryPowerPred')
# DebugFlag('SimplePowerPred')
# DebugFlag('SensorPowerPred')
# DebugFlag('uArchEventPowerPred')
DebugFlag('HarvardPowerPred')
# DebugFlag('DecorOnlyPowerPred')
# DebugFlag('PerceptronPowerPred')
# DebugFlag('PerceptronUTAPowerPred')
# DebugFlag('DNNPowerPred')
# DebugFlag('ThrottleAfterStallPowerPred')
# DebugFlag('DepAnalysisPowerPred')
Source('ppred_unit.cc')
Source('test.cc')
# Source('simple_history.cc')
# Source('simple.cc')
# Source('sensor.cc')
# Source('decor_only.cc')
# Source('uarch_event.cc')
Source('harvard.cc')
# Source('perceptron_predictor.cc')
# Source('perceptron_predictor_uta.cc')
# Source('dnn_predictor.cc')
# Source('throttle_after_stall.cc')
# Source('dependency_analysis.cc')

Source('mcpat.cc')
Source('mcpat_update.cc')
Source('pdn.cc')

DebugFlag('PredictionTable')
DebugFlag('HistoryRegister')
DebugFlag('PPredStat')
Source('prediction_table.cc')
Source('history_register.cc')
Source('event_type.cc')
Source('ppred_stat.cc')
